### ISSUE TITLE
Why no react-native?

### ISSUE THREAD

**Issue by Segfaultd** [GuiTeK/FonGuard#1]
I mean Android is shit, so could be fun to have it hybrid :D

**Comment by GuiTeK** [comment]
Ahah :trollface: I use many Android-specific features/permissions and some low level stuff (e.g. to send MMS). Also some of the things I do in this app are completely impossible in iOS (send SMS in the background, use the camera in the background, etc.).

**Comment by Segfaultd** [comment]
Seems legit. Gonna close the issue. Thanks for reporting m8
